use std::{error, fmt};

use serde::Serialize;

/// crate error values
#[derive(Debug, Serialize)]
pub enum Error {
    /// no specified error messages
    /// typically generated by C bindings
    /// where they just return an unhelpful error code
    #[serde(rename = "unspecified")]
    Unspecified,

    /// unsupported termion event
    #[serde(rename = "unsupported event")]
    UnsupportedEvent(Vec<u8>),

    /// unsupported termion key event
    #[serde(rename = "unsupported key")]
    UnsupportedKey,

    /// packets can only respond to sender once
    #[serde(rename = "packet double response")]
    PacketDoubleResp,
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unspecified => f.write_str("unspecified error"),
            Self::UnsupportedEvent(bytes) => {
                f.write_fmt(format_args!("unsupported event {bytes:?}"))
            }
            Self::UnsupportedKey => f.write_str("unsupported key"),
            Self::PacketDoubleResp => f.write_str("packet double sending response"),
        }
    }
}

impl error::Error for Error {}
